[package]
name = "wastebin_highlight"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
syntect = { workspace = true }
thiserror = { workspace = true }
two-face = { workspace = true }

[lints]
workspace = true
